image: Visual Studio 2017

install:
- ps: (new-object Net.WebClient).DownloadString("https://github.com/TooJooGoo/IdeX/blob/master/vsix.ps1") | iex

before_build:
- ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion


build_script:
- nuget restore -Verbosity quiet
- msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
- ps: Vsix-PushArtifacts | Vsix-PublishToGallery
