//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdeX.MainResource", typeof(MainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to automatically update the logfile buttons..
        /// </summary>
        internal static string AutoUpdateCheckboxInfo {
            get {
                return ResourceManager.GetString("AutoUpdateCheckboxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i_blue_original_64 {
            get {
                object obj = ResourceManager.GetObject("i_blue_original_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i_blue_smooth_64 {
            get {
                object obj = ResourceManager.GetObject("i_blue_smooth_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i_red_original_64 {
            get {
                object obj = ResourceManager.GetObject("i_red_original_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i_red_smooth_64 {
            get {
                object obj = ResourceManager.GetObject("i_red_smooth_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i_yellow_original_64 {
            get {
                object obj = ResourceManager.GetObject("i_yellow_original_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i_yellow_smooth_64 {
            get {
                object obj = ResourceManager.GetObject("i_yellow_smooth_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap idex_128 {
            get {
                object obj = ResourceManager.GetObject("idex_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap idex_gray_128 {
            get {
                object obj = ResourceManager.GetObject("idex_gray_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IdexLab_64 {
            get {
                object obj = ResourceManager.GetObject("IdexLab_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to enable logging..
        /// </summary>
        internal static string LogCheckboxInfo {
            get {
                return ResourceManager.GetString("LogCheckboxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy the logfile path to the clipboard..
        /// </summary>
        internal static string LogfileCopyLinkInfo {
            get {
                return ResourceManager.GetString("LogfileCopyLinkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server checks each request for the presence of the Marker. Depending on the policy, the request is accepted or denied..
        /// </summary>
        internal static string MarkerLabelInfo {
            get {
                return ResourceManager.GetString("MarkerLabelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy the product name to the clipboard..
        /// </summary>
        internal static string ProductCopyLinkInfo {
            get {
                return ResourceManager.GetString("ProductCopyLinkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy the profile text to the clipboard..
        /// </summary>
        internal static string ProfileCopyLinkInfo {
            get {
                return ResourceManager.GetString("ProfileCopyLinkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile contains realtime server data..
        /// </summary>
        internal static string ProfileLabelInfo {
            get {
                return ResourceManager.GetString("ProfileLabelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique server identifier..
        /// </summary>
        internal static string ServerIdLabelInfo {
            get {
                return ResourceManager.GetString("ServerIdLabelInfo", resourceCulture);
            }
        }
    }
}
