// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IdeX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string IdexPackageGuidString = "833a1a1b-dac5-410f-9a56-911dd2c15ee1";
        public const string IdexMenuGroupGuidString = "a8ec82cd-2a2d-47ec-b310-f1c255c560de";
        public const string IdexBitmapGuidString = "ad117804-b44f-45bc-9402-0e46d1e1dd05";
        public static Guid IdexPackageGuid = new Guid(IdexPackageGuidString);
        public static Guid IdexMenuGroupGuid = new Guid(IdexMenuGroupGuidString);
        public static Guid IdexBitmapGuid = new Guid(IdexBitmapGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IdexMenuGroup = 0x1100;
        public const int ToolsGroup = 0x1020;
        public const int OptionsMenuGroup = 0x1150;
        public const int ActionsMenuGroup = 0x1151;
        public const int OptionsButton = 0x0101;
        public const int ExpertButton = 0x0102;
        public const int EnableButton = 0x0103;
        public const int DisableButton = 0x0104;
        public const int LabButton = 0x0105;
        public const int IdexIconPictureId = 0x0001;
    }
}
